name: "Download Comparison Artifacts"
description: "Downloads artifacts needed for run comparison"
inputs:
  report-artifact-name:
    required: true
  binary-artifact-name:
    required: true
  github-token:
    required: true

runs:
  using: "composite"
  steps:
    - name: Download report from this workflow
      if: '!cancelled()'
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.report-artifact-name }}
        path: "./logs"
      continue-on-error: true

    - name: Download report from another workflow
      if: ${{ !cancelled() && hashFiles(format('./logs/{0}', inputs.report-artifact-name)) == '' }}
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{ inputs.github-token }}
        workflow: build-frequent.yaml
        workflow_conclusion: ""
        name: ${{ inputs.report-artifact-name }}
        search_artifacts: true
        path: "./logs"
      continue-on-error: true

    - name: Download rv32 non-multilib binary
      if: ${{ !cancelled() && hashFiles(format('./logs/{0}', inputs.report-artifact-name)) == '' }}
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.binary-artifact-name }}
        path: "./temp"
      continue-on-error: true

    - name: Download rv32 non-multilib binary from another workflow
      if: ${{ !cancelled() && hashFiles(format('./logs/{0}', inputs.report-artifact-name)) == '' }} && hashFiles(format('./temp/{0}', inputs.binary-artifact-name))
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{ inputs.github-token }}
        workflow: build-frequent.yaml
        workflow_conclusion: ""
        name: ${{ inputs.binary-artifact-name }}
        search_artifacts: true
        path: "./temp"
      continue-on-error: true