name: Build-Frequent

on:
  push:
    branches:
      - build-frequent
  pull_request:
    branches:
      - build-frequent
  schedule:
    # Run 4 times a day
    - cron: 0 0,6,12,18 * * *
  workflow_dispatch:
    branches:
      - build-frequent
    inputs:
      gcchash:
        description: 'GCC Hash'
        required: true
      multi_target:
        description: 'Targets to run (libc:arch-abi;...)'
        required: true
      issue_num:
        description: 'Bisection Issue Number (Optional)'
        required: false

jobs:
  init-submodules:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Retrieve cache
        id: retrieve-cache
        uses: actions/cache@v3
        with:
          path: |
            .git
            binutils
            dejagnu
            gcc
            gdb
            glibc
            newlib
            qemu
          key: submodules-archive-2 # Numbered archive to allow for easy transition when bumping submodules

      - name: Initalize submodules cache
        if: steps.retrieve-cache.outputs.cache-hit != 'true'
        run: |
          git submodule update --init --recursive --depth 1 binutils
          git submodule update --init --recursive --depth 1 dejagnu
          git submodule update --init --recursive --depth 1 gdb
          git submodule update --init --recursive --depth 1 glibc
          git submodule update --init --recursive --depth 1 newlib
          git submodule update --init --recursive --depth 1 qemu
          rm -rf gcc
          git clone git://gcc.gnu.org/git/gcc.git

      - name: Get GCC hash
        id: gcc-hash
        run: |
          cd gcc
          git checkout master
          git pull
          if [ "${{ github.event.inputs.gcchash }}" == "" ]; then
            export GCCHASH=$(git rev-parse HEAD)
          else
            export GCCHASH=${{ github.event.inputs.gcchash }}
          fi
          echo $GCCHASH
          echo "gcchash=$GCCHASH" >> "$GITHUB_OUTPUT"

      - name: Cache submodules
        if: steps.retrieve-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: |
            .git
            binutils
            dejagnu
            gcc
            gdb
            glibc
            newlib
            qemu
          key: submodules-archive-2

      - name: Make cache zip
        run: |
          zip -r cache.zip .git binutils dejagnu gcc gdb glibc newlib qemu

      # Use artifact rather than cache since cache downloads are flaky/hang.
      # Artifacts are reliable but ~30 min slower to set up.
      # Setup is done on one runner, so this isn't a show stopper.
      - name: Upload git cache
        uses: actions/upload-artifact@v3
        with:
          name: gcc-sources-${{ steps.gcc-hash.outputs.gcchash }}
          path: |
            cache.zip
          retention-days: 5

    outputs:
      gcchash: ${{ steps.gcc-hash.outputs.gcchash }}

  creg: # Check Regressions. Short name so I can see the matrix string in github
    needs: [init-submodules]
    strategy:
      fail-fast: false
      matrix:
        mode: [newlib, linux]
        target:
          [
            rv32gcv-ilp32d, # rv32 vector
            rv64gcv-lp64d, # rv64 vector
            rv32gc_zba_zbb_zbc_zbs-ilp32d, # rv32 bitmanip
            rv64gc_zba_zbb_zbc_zbs-lp64d, # rv64 bitmanip
            rv32gcv_zvbb_zvbc_zvkg_zvkn_zvknc_zvkned_zvkng_zvknha_zvknhb_zvks_zvksc_zvksed_zvksg_zvksh_zvkt-ilp32d, # rv32 vector crypto
            rv64gcv_zvbb_zvbc_zvkg_zvkn_zvknc_zvkned_zvkng_zvknha_zvknhb_zvks_zvksc_zvksed_zvksg_zvksh_zvkt-lp64d, # rv64 vector crypto
            rv64imafdcv_zicond_zawrs_zbc_zvkng_zvksg_zvbb_zvbc_zicsr_zba_zbb_zbs_zicbom_zicbop_zicboz_zfhmin_zkt-lp64d, # RVA23U64 profile with optional extensions, excluding unsupported extensions
          ]
        multilib: [non-multilib]
    uses: ./.github/workflows/regression-runner.yaml
    with:
      mode: ${{ matrix.mode }}
      target: ${{ matrix.target }}
      gcchash: ${{ needs.init-submodules.outputs.gcchash }}
      multilib: ${{ matrix.multilib }}
      multitarget: ${{ github.event.inputs.multi_target }}
      run_on_self_hosted: false

  cmreg: # Check Multilib Regressions. Short name so I can see the matrix string in github
    needs: [init-submodules]
    strategy:
      fail-fast: false
      matrix:
        mode: [newlib]
        target: [rv64gc-lp64d] # Dummy placeholder. Actually runs rv32/rv64 multilib
        multilib: [multilib]
    uses: ./.github/workflows/regression-runner.yaml
    with:
      mode: ${{ matrix.mode }}
      target: ${{ matrix.target }}
      gcchash: ${{ needs.init-submodules.outputs.gcchash }}
      multilib: ${{ matrix.multilib }}
      multitarget: ${{ github.event.inputs.multi_target }}
      run_on_self_hosted: false

  cmreg-self-hosted: # Check Multilib Regressions. Short name so I can see the matrix string in github
    needs: [init-submodules]
    strategy:
      fail-fast: false
      matrix:
        mode: [linux]
        target: [rv64gc-lp64d] # Dummy placeholder. Actually runs rv32/rv64 multilib
        multilib: [multilib]
    uses: ./.github/workflows/regression-runner.yaml
    with:
      mode: ${{ matrix.mode }}
      target: ${{ matrix.target }}
      gcchash: ${{ needs.init-submodules.outputs.gcchash }}
      multilib: ${{ matrix.multilib }}
      multitarget: ${{ github.event.inputs.multi_target }}
      run_on_self_hosted: true

  build-x86:
    if: ${{ false }} # Temporarily disable x86. Should be re-enabled to only run when a build failure occurs.
    needs: [init-submodules, creg, cmreg]
    uses: ./.github/workflows/bootstrap-x86.yaml
    with:
      gcchash: ${{ needs.init-submodules.outputs.gcchash }}

  summarize:
    if: "!cancelled()" # Generate github issues even when some (or all) targets fail to build
    needs: [init-submodules, creg, cmreg, cmreg-self-hosted]
    permissions:
      issues: write
    uses: ./.github/workflows/generate-summary.yaml
    with:
      gcchash: ${{ needs.init-submodules.outputs.gcchash }}
      issue_num: ${{ github.event.inputs.issue_num }}
