name: CI Playground

on:
  push:
    branches:
      - ci-playground

jobs:
  testfiles:
    runs-on: ubuntu-22.04

    steps:
      - name: Make file
        run: |
          echo "ok" > test.txt

      - name: if file exists
        if: ${{ hashFiles('test.txt') != '' }}
        run: |
          echo "File exists"
          echo "ok" > test2.txt

      - name: if file doesn't exist
        if: ${{ hashFiles('test.txt') == '' }}
        run: echo "File doesn't exist"

      - name: if both files exist
        if: ${{ !cancelled() && hashFiles('test.txt') != '' || hashFiles('test2.txt') != '' }}
        run: echo "File doesn't exist"

      - name: if both files don't exist
        if: ${{ !cancelled() && hashFiles('test.txt') == '' && hashFiles('test2.txt') == '' }}
        run: echo "File doesn't exist"
