name: Native-Regression-Runner

on:
  push:
    branches:
      - native-builds
  pull_request:
    branches:
      - build-frequent

jobs:
  build:
    runs-on: ubuntu-22.04
    environment: production
    steps:
      - name: Remove unneeded frameworks to recover disk space
        run: |
          echo "-- Before --"
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          echo "-- After --"
          df -h

      - uses: actions/checkout@v3

      - name: Restore submodules from cache
        uses: actions/download-artifact@v3
        with:
          name: gcc-sources-${{ inputs.gcchash }}

      - name: Restore submodules
        run: |
          rm -rf .git binutils dejagnu gcc gdb glibc musl newlib pk qemu
          unzip cache.zip

      - name: Checkout gcc hash
        run: |
          cd gcc
          git fetch
          git checkout ${{ inputs.gcchash }}

      - name: Install dependencies
        run: sudo ./.github/setup-apt.sh

      - name: Configure
        run: |
          mkdir build
          cd build
          ../configure --prefix=$(pwd)

      - name: Make gcc
        run: |
          cd build
          make -j $(nproc) linux-native

      - name: Remove sources to reclaim disk space
        run: |
          rm -rf .git binutils dejagnu gcc gdb glibc musl newlib pk qemu

      - name: Zip binaries
        run: |
          zip -r bin.zip build/bin

      - name: Upload binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: gcc-binaries
          path: |
            bin.zip
          retention-days: 5
