name: Native-Regression-Runner

on:
  push:
    branches:
      - native-builds
  pull_request:
    branches:
      - build-frequent

jobs:
  build:
    runs-on: ubuntu-22.04
    environment: production
    steps:
      - name: Remove unneeded frameworks to recover disk space
        run: |
          echo "-- Before --"
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          echo "-- After --"
          df -h

      - uses: actions/checkout@v3

      - name: Build GCC
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: riscv64
          distro: ubuntu-22.04
          run: |
            echo "Hello!"
