name: Pre-Pull-Request

on:
  push:
    branches:
      - build-frequent
  pull_request:
    branches:
      - build-frequent

jobs:
  pytest:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Test with pytest
        run: |
          pytest test/pytests
