name: x86-regression-runner

on:
  workflow_call:
    inputs:
      gcchash:
        required: true
        type: string

# Original source: https://github.com/gcc-mirror/gcc/pull/88

jobs:
  build:
    name: ubuntu-x86_64-build
    runs-on: ubuntu-latest
    steps:
      - name: Remove unneeded frameworks to recover disk space
        run: |
          echo "-- Before --"
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          echo "-- After --"
          df -h

      - uses: actions/checkout@v3

      - name: Restore submodules from cache
        uses: actions/download-artifact@v3
        with:
          name: gcc-sources-${{ inputs.gcchash }}

      - name: Restore submodules
        run: |
          rm -rf .git binutils dejagnu gcc gdb glibc musl newlib pk qemu
          unzip cache.zip

      - name: Checkout gcc hash
        run: |
          cd gcc
          git fetch
          git checkout ${{ inputs.gcchash }}

      - name: Install dependencies
        run: |
          sudo apt-get -qq update
          sudo apt install -y gcc-multilib build-essential flex zlib1g-dev gnat gdc

      - name: Download prerequisites
        run: |
          cd gcc
          ./contrib/download_prerequisites

      - name: Configure x86_64
        run: |
          unset ADA_INCLUDE_PATH
          unset ADA_OBJECT_PATH
          mkdir build
          cd build
          ../gcc/configure \
                --enable-languages=c,c++,go,d,fortran,objc,obj-c++,m2 \
                --prefix=/usr \
                --with-gcc-major-version-only \
                --program-prefix=x86_64-linux-gnu- \
                --enable-shared \
                --enable-linker-build-id \
                --libexecdir=/usr/lib \
                --without-included-gettext \
                --enable-threads=posix \
                --libdir=/usr/lib \
                --enable-nls \
                --enable-clocale=gnu \
                --enable-libstdcxx-debug \
                --enable-libstdcxx-time=yes \
                --with-default-libstdcxx-abi=new \
                --enable-gnu-unique-object \
                --disable-vtable-verify \
                --enable-plugin \
                --enable-default-pie \
                --with-system-zlib \
                --with-target-system-zlib=auto \
                --enable-objc-gc=auto \
                --enable-multiarch \
                --disable-werror \
                --with-arch-32=i686 \
                --with-abi=m64 \
                --with-tune=generic \
                --without-cuda-driver \
                --enable-checking=release \
                --build=x86_64-linux-gnu \
                --host=x86_64-linux-gnu \
                --target=x86_64-linux-gnu

      - name: Make bootstrap
        run: |
          cd build
          make bootstrap -j$(nproc)

      - name: Make install
        run: |
          cd build
          sudo make install

      - name: Make check
        run: |
          cd build
          make -k check -j$(nproc) || true

      - name: Save results
        run: |
          PARSE_EXISTING_REPORT="./scripts/testsuite-filter gcc newlib test/allowlist `find build/build-gcc-newlib-stage2/gcc/testsuite/ -name *.sum |paste -sd "," -`"
          $PARSE_EXISTING_REPORT | tee gcc-newlib-x86_64-${{ inputs.gcchash }}-report.log

      - name: Upload results artifact
        uses: actions/upload-artifact@v3
        with:
          name: gcc-newlib-x86_64-${{ inputs.gcchash }}-report.log
          path: |
            gcc-newlib-x86_64-${{ inputs.gcchash }}-report.log
          retention-days: 90
